#!/usr/bin/env python3
"""
Auto-generate imperfect + present-subjunctive example sentences for every verb
in conjugations.py that doesn't have them yet. Uses fixed-meaning Spanish/English
template sentences that work for any verb, with the conjugated form spliced in.

Outputs: _tools/generated_sentences.py — a dict of verb → tense → sentence list.
You then merge this into conjugations.py by hand or via the merger script.

Templates are intentionally simple and unambiguous so each card teaches the form,
not vocabulary the learner doesn't yet have.
"""
import sys, os, json
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from conjugations import (
    VERBS, REGULAR_ENDINGS, IRREGULAR_IMPERFECT, IRREGULAR_SUBJ_PRESENT
)


def get_forms(verb, type_, declared, tense):
    declared = declared or {}
    if tense in declared:
        return declared[tense]
    if tense == 'imperfect' and verb in IRREGULAR_IMPERFECT:
        return IRREGULAR_IMPERFECT[verb]
    if tense == 'subjunctive_present' and verb in IRREGULAR_SUBJ_PRESENT:
        return IRREGULAR_SUBJ_PRESENT[verb]
    ending = verb[-2:]
    stem = verb[:-2]
    return [stem + suf for suf in REGULAR_ENDINGS[ending][tense]]


# English bare verb (for "used to X" / "that X") — drop the leading "to "
def en_bare(english_meaning):
    s = english_meaning.split('/')[0].split('(')[0].strip()
    if s.lower().startswith('to '):
        s = s[3:]
    return s.strip()


# ─── Imperfect templates ──────────────────────────────────────────────
# Each template is (es_sentence_with_$V, en_sentence_with_$V)
IMP_TEMPLATES = [
    ('Cuando era niño, yo $V mucho.',
     'When I was a kid, I used to $V a lot.'),
    ('Tú $V todos los días.',
     'You used to $V every day.'),
    ('Ella $V de joven.',
     'She used to $V when she was young.'),
    ('Nosotros $V juntos en aquellos años.',
     'We used to $V together in those years.'),
    ('Ellos $V cada tarde.',
     'They used to $V every afternoon.'),
]

# ─── Subjunctive present templates ────────────────────────────────────
# After "que" + a trigger of doubt/desire/emotion.
SUBJ_TEMPLATES = [
    ('Quieren que yo $V.',
     'They want me to $V.'),
    ('Espero que tú $V pronto.',
     'I hope you $V soon.'),
    ('Es importante que ella $V.',
     'It is important that she $V.'),
    ('Dudo que nosotros $V hoy.',
     'I doubt that we $V today.'),
    ('Ojalá que ellos $V bien.',
     'I hope they $V well.'),
]


def render(template_es, template_en, conj_form, en_form):
    return (template_es.replace('$V', conj_form),
            template_en.replace('$V', en_form))


def main():
    out = {}
    for verb, info in VERBS.items():
        forms_imp  = get_forms(verb, info['type'], info.get('forms'), 'imperfect')
        forms_subj = get_forms(verb, info['type'], info.get('forms'), 'subjunctive_present')
        en = en_bare(info['english'])

        out[verb] = {
            'imperfect': [
                render(IMP_TEMPLATES[i][0], IMP_TEMPLATES[i][1], forms_imp[i], en)
                for i in range(5)
            ],
            'subjunctive_present': [
                render(SUBJ_TEMPLATES[i][0], SUBJ_TEMPLATES[i][1], forms_subj[i], en)
                for i in range(5)
            ],
        }

    # Output as a Python literal we can paste / merge
    out_path = os.path.join(os.path.dirname(__file__), 'generated_sentences.py')
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write('# Auto-generated by augment_sentences.py — DO NOT EDIT BY HAND.\n')
        f.write('# Merged into conjugations.py via merge_sentences.py.\n\n')
        f.write('GENERATED = ')
        # Pretty-print with deterministic ordering
        f.write(repr(out))
        f.write('\n')

    print(f'✅ {out_path}')
    print(f'   verbs: {len(out)}')
    print(f'   sentences: {len(out) * 10}')


if __name__ == '__main__':
    main()
