#!/usr/bin/env python3
"""
Build data.js from a flat Python vocabulary list. Validates each entry and
merges with the canonical category-color and emoji maps. The new VOCABULARY
format supports per-word visual strategy:

    [spanish, english, category, image_search, visual_strategy, usage_example?]

Strategies:
    photo    - fetched Pixabay image (default for concrete things)
    digit    - render the digit large (numbers)
    swatch   - solid color block (colors)
    text     - English word as visual (abstract / category headers)
    grammar  - the English word + a short usage example (uses 6th field)
"""
import json, os, sys, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Visual strategies allowed
STRATS = {'photo', 'digit', 'swatch', 'text', 'grammar'}

# Category colors — additions on top of original 25
CAT_COLORS = {
    "greetings": "#E3F2FD", "people":    "#FCE4EC", "family":     "#FFF3E0",
    "numbers":   "#F3E5F5", "colors":    "#E8F5E9", "food":       "#FFF8E1",
    "body":      "#FFEBEE", "home":      "#E0F2F1", "time":       "#EDE7F6",
    "places":    "#E1F5FE", "transport": "#F9FBE7", "verbs":      "#F1F8E9",
    "adjectives":"#FBE9E7", "connectors":"#ECEFF1", "weather":    "#E3F2FD",
    "nature":    "#E8F5E9", "health":    "#FCE4EC", "work":       "#FFF3E0",
    "school":    "#E8EAF6", "tech":      "#E0F7FA", "mexican":    "#FFF9C4",
    "shopping":  "#F3E5F5", "directions":"#E0F2F1", "emergency":  "#FFEBEE",
    "basics":    "#ECEFF1",
    # New
    "abstract":   "#F3F0E8", "emotion":    "#FCE4EC",
    "agriculture":"#FFF8E1", "wine":       "#F3E5F5",
    "objects":    "#F5F0E8", "music":      "#D1C4E9",
    "arts":       "#E1BEE7", "sports":     "#FFE0B2",
    "science":    "#B3E5FC", "animals":    "#E8F5E9",
}

# Fallback emoji per category (used only as last-resort, image is primary now)
CATEGORY_EMOJI = {
    "greetings": "👋", "people": "🧑", "family": "👪",
    "numbers": "🔢", "colors": "🎨", "food": "🍽️",
    "body": "🫀", "home": "🏠", "time": "⏰",
    "places": "📍", "transport": "🚗", "verbs": "⚡",
    "adjectives": "✨", "connectors": "🔗", "weather": "⛅",
    "nature": "🌿", "health": "🩺", "work": "💼",
    "school": "📚", "tech": "💻", "mexican": "🇲🇽",
    "shopping": "🛍️", "directions": "🧭", "emergency": "🚨",
    "basics": "💬",
    "abstract": "💭", "emotion": "❤️",
    "agriculture": "🌾", "wine": "🍇",
    "objects": "📦", "music": "🎵", "arts": "🎨",
    "sports": "⚽", "science": "🔬", "animals": "🐾",
}


def validate(vocab):
    errs = []
    for i, entry in enumerate(vocab):
        if not isinstance(entry, list):
            errs.append(f'#{i} not a list')
            continue
        if len(entry) < 4 or len(entry) > 6:
            errs.append(f'#{i} bad length: {entry!r}')
            continue
        sp, en, cat, search = entry[:4]
        if not isinstance(sp, str) or not sp:
            errs.append(f'#{i} bad spanish: {entry!r}')
        if not isinstance(en, str) or not en:
            errs.append(f'#{i} bad english: {entry!r}')
        if cat not in CAT_COLORS:
            errs.append(f'#{i} unknown category {cat!r} ({sp})')
        if len(entry) >= 5 and entry[4] and entry[4] not in STRATS:
            errs.append(f'#{i} bad strategy {entry[4]!r} ({sp})')
        if len(entry) == 6 and entry[4] != 'grammar':
            errs.append(f'#{i} usage example only allowed with grammar ({sp})')
    return errs


def write_data_js(vocab, out_path):
    header = (
        "// ─────────────────────────────────────────────────────────────────────\n"
        "// Spanish Tutor — vocabulary and emoji data\n"
        "// Auto-generated by _tools/build_data.py — edit the Python source instead.\n"
        "// ─────────────────────────────────────────────────────────────────────\n\n"
        "// Each entry: [spanish, english, category, image_search,\n"
        "//              visual_strategy?, usage_example?]\n"
        "//\n"
        "// visual_strategy is one of: photo, digit, swatch, text, grammar\n"
    )
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(header)
        f.write('const VOCABULARY = ')
        f.write(json.dumps(vocab, ensure_ascii=False, indent=2))
        f.write(';\n\n')
        # EMOJI_MAP retained for backward compat but no longer primary
        emoji_path = os.path.join(ROOT, 'data.js')
        prev = open(emoji_path, encoding='utf-8').read() if os.path.exists(emoji_path) else ''
        m = re.search(r'const EMOJI_MAP = (\{.*?\n\});', prev, re.DOTALL)
        if m:
            f.write('const EMOJI_MAP = ' + m.group(1) + ';\n\n')
        else:
            f.write('const EMOJI_MAP = {};\n\n')
        f.write('const CATEGORY_EMOJI = ')
        f.write(json.dumps(CATEGORY_EMOJI, ensure_ascii=False, indent=2))
        f.write(';\n\n')
        f.write('const CAT_COLORS = ')
        f.write(json.dumps(CAT_COLORS, ensure_ascii=False, indent=2))
        f.write(';\n')


def write_index_manifest(vocab):
    """Save a tiny CSV mapping idx → spanish word. Used to detect order changes
    between builds, so we never leave audio/{idx}.mp3 mismatched with vocabulary[idx]
    again. Compare with previous to catch reordering."""
    path = os.path.join(ROOT, '_tools', 'index_manifest.tsv')
    prev = {}
    if os.path.exists(path):
        for line in open(path, encoding='utf-8'):
            i, sp = line.rstrip('\n').split('\t', 1)
            prev[int(i)] = sp
    with open(path, 'w', encoding='utf-8') as f:
        for i, e in enumerate(vocab):
            f.write(f'{i}\t{e[0]}\n')
    if prev:
        moved = [(i, prev[i], vocab[i][0]) for i in prev
                 if i < len(vocab) and prev[i] != vocab[i][0]]
        if moved:
            print(f'⚠️  {len(moved)} entries changed at fixed indices —')
            print(f'   audio/images at those indices may now be stale.')
            print(f'   Run:  python3 _tools/generate_audio.py --regen-all')
            print(f'   And:  PIXABAY_KEY=... python3 _tools/fetch_images.py')
            for i, old, new in moved[:5]:
                print(f'   #{i}: {old!r} → {new!r}')


if __name__ == '__main__':
    # Import the word list from a sibling Python file
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    from vocabulary import VOCABULARY

    errs = validate(VOCABULARY)
    if errs:
        print(f'{len(errs)} validation error(s):')
        for e in errs[:20]:
            print('  ', e)
        if len(errs) > 20:
            print(f'  …and {len(errs)-20} more')
        sys.exit(1)

    out = os.path.join(ROOT, 'data.js')
    write_data_js(VOCABULARY, out)
    write_index_manifest(VOCABULARY)
    print(f'✅ wrote {out} with {len(VOCABULARY)} entries')
