# Spanish Tutor — full vocabulary source
# Edit this file, then run:  python3 _tools/build_data.py
#
# Each entry:  [spanish, english, category, image_search,
#               visual_strategy, usage_example?]
#
# Strategies:
#   photo    real Pixabay photo of the thing
#   digit    big rendered number (for specific digits)
#   swatch   solid color block (for specific colors)
#   text     English word rendered as a card (abstract / category names)
#   grammar  English word + a short usage example (pure function words)

VOCABULARY = [

# ─── GREETINGS & SOCIAL ─────────────────────────────────────────────
["hola","hello","greetings","friendly greeting wave","photo"],
["adiós","goodbye","greetings","waving goodbye sunset","photo"],
["por favor","please","greetings","polite please hands","photo"],
["gracias","thank you","greetings","thankful gesture","photo"],
["de nada","you're welcome","greetings","welcome smile","photo"],
["perdón","excuse me / sorry","greetings","sorry apologize","photo"],
["buenos días","good morning","greetings","morning sunrise coffee","photo"],
["buenas tardes","good afternoon","greetings","afternoon sun warm","photo"],
["buenas noches","good night","greetings","night moon stars","photo"],
["¿cómo estás?","how are you?","greetings","friends greeting","photo"],
["mucho gusto","nice to meet you","greetings","handshake meet","photo"],
["con permiso","excuse me (passing)","greetings","crowd passing","photo"],
["bienvenido","welcome","greetings","welcome doormat","photo"],
["salud","cheers / bless you","greetings","toast cheers glasses","photo"],

# ─── BASICS ─────────────────────────────────────────────────────────
["sí","yes","basics","nod yes thumbs up","photo"],
["no","no","basics","crossed arms refusal","photo"],
["tal vez","maybe / perhaps","basics","","text"],
["bien","good / fine / well","basics","","text"],
["mal","bad / poorly","basics","","text"],
["más o menos","so-so / more or less","basics","","text"],
["¿qué?","what?","basics","","text"],
["¿cómo?","how? / pardon?","basics","","text"],
["¿por qué?","why?","basics","","text"],
["porque","because","basics","","grammar","I stayed home because it was raining."],

# ─── PEOPLE ─────────────────────────────────────────────────────────
["hombre","man","people","adult man portrait","photo"],
["mujer","woman","people","adult woman portrait","photo"],
["niño","boy / child","people","young boy child","photo"],
["niña","girl / child","people","young girl child","photo"],
["bebé","baby","people","baby infant","photo"],
["persona","person","people","person individual","photo"],
["gente","people","people","crowd people group","photo"],
["amigo","friend (male)","people","male friends laughing","photo"],
["amiga","friend (female)","people","female friends laughing","photo"],

# ─── FAMILY ─────────────────────────────────────────────────────────
["familia","family","family","family together portrait","photo"],
["madre","mother","family","mother child","photo"],
["padre","father","family","father child","photo"],
["mamá","mom","family","mom hug","photo"],
["papá","dad","family","dad child","photo"],
["hermano","brother","family","brothers together","photo"],
["hermana","sister","family","sisters together","photo"],
["hijo","son","family","son boy family","photo"],
["hija","daughter","family","daughter girl family","photo"],
["abuelo","grandfather","family","grandfather elderly man","photo"],
["abuela","grandmother","family","grandmother elderly woman","photo"],
["tío","uncle","family","uncle man family","photo"],
["tía","aunt","family","aunt woman family","photo"],
["primo","male cousin","family","cousins boys","photo"],
["prima","female cousin","family","cousins girls","photo"],
["esposo","husband","family","husband wedding","photo"],
["esposa","wife","family","wife wedding","photo"],
["novio","boyfriend","family","boyfriend couple","photo"],
["novia","girlfriend","family","girlfriend couple","photo"],

# ─── NUMBERS (digit rendering) ──────────────────────────────────────
["uno","one","numbers","1","digit"],
["dos","two","numbers","2","digit"],
["tres","three","numbers","3","digit"],
["cuatro","four","numbers","4","digit"],
["cinco","five","numbers","5","digit"],
["seis","six","numbers","6","digit"],
["siete","seven","numbers","7","digit"],
["ocho","eight","numbers","8","digit"],
["nueve","nine","numbers","9","digit"],
["diez","ten","numbers","10","digit"],
["veinte","twenty","numbers","20","digit"],
["cincuenta","fifty","numbers","50","digit"],
["cien","one hundred","numbers","100","digit"],
["mil","one thousand","numbers","1,000","digit"],

# ─── COLORS (solid color swatches) ──────────────────────────────────
["rojo","red","colors","#E53935","swatch"],
["azul","blue","colors","#1565C0","swatch"],
["verde","green","colors","#43A047","swatch"],
["amarillo","yellow","colors","#FDD835","swatch"],
["negro","black","colors","#212121","swatch"],
["blanco","white","colors","#FAFAFA","swatch"],
["naranja","orange","colors","#FB8C00","swatch"],
["morado","purple","colors","#6A1B9A","swatch"],
["rosa","pink","colors","#EC407A","swatch"],
["café","brown","colors","#6D4C41","swatch"],
["gris","gray","colors","#757575","swatch"],
["dorado","golden / gold","colors","#FFC107","swatch"],

# ─── FOOD & DRINK ───────────────────────────────────────────────────
["comida","food","food","delicious food plate","photo"],
["agua","water","food","glass of water clear","photo"],
["leche","milk","food","glass of milk","photo"],
["café","coffee","food","coffee cup espresso","photo"],
["jugo","juice","food","fresh orange juice","photo"],
["cerveza","beer","food","cold beer glass","photo"],
["vino","wine","food","red wine glass","photo"],
["pan","bread","food","fresh bread loaf","photo"],
["arroz","rice","food","bowl of rice","photo"],
["frijoles","beans","food","black beans bowl","photo"],
["carne","meat","food","grilled steak meat","photo"],
["pollo","chicken","food","roasted chicken","photo"],
["pescado","fish","food","grilled fish fillet","photo"],
["huevo","egg","food","fried egg yolk","photo"],
["queso","cheese","food","cheese wheel","photo"],
["tortilla","tortilla","food","corn tortilla stack","photo"],
["tacos","tacos","food","mexican tacos street","photo"],
["salsa","salsa / sauce","food","salsa sauce bowl","photo"],
["chile","chili pepper","food","red chili pepper","photo"],
["limón","lime","food","lime green citrus","photo"],
["aguacate","avocado","food","avocado halved","photo"],
["tomate","tomato","food","red tomato fresh","photo"],
["cebolla","onion","food","onion white","photo"],
["ajo","garlic","food","garlic cloves","photo"],
["manzana","apple","food","red apple fruit","photo"],
["plátano","banana","food","banana yellow","photo"],
["fresas","strawberries","food","fresh strawberries","photo"],
["dulce","sweet / candy","food","candy colorful","photo"],
["azúcar","sugar","food","sugar spoon white","photo"],
["sal","salt","food","salt shaker","photo"],
["sopa","soup","food","bowl of soup steaming","photo"],
["sandwich","sandwich","food","sandwich","photo"],
["ensalada","salad","food","fresh garden salad","photo"],
["postre","dessert","food","dessert sweet plate","photo"],
["helado","ice cream","food","ice cream scoop cone","photo"],
["chocolate","chocolate","food","dark chocolate bar","photo"],
["desayuno","breakfast","food","breakfast pancakes plate","photo"],
["almuerzo","lunch","food","lunch midday meal","photo"],
["cena","dinner","food","dinner table evening","photo"],

# ─── MEXICAN FOOD ───────────────────────────────────────────────────
["torta","Mexican sandwich","food","mexican torta sandwich","photo"],
["quesadilla","quesadilla","food","quesadilla cheese","photo"],
["tamales","tamales","food","tamales corn husk","photo"],
["pozole","pozole (hominy soup)","food","pozole mexican soup","photo"],
["mole","mole sauce","food","mole sauce mexican","photo"],
["elote","corn on the cob","food","corn elote grilled","photo"],
["guacamole","guacamole","food","guacamole avocado dip","photo"],
["enchiladas","enchiladas","food","enchiladas mexican","photo"],
["chiles rellenos","stuffed peppers","food","chiles rellenos","photo"],
["horchata","horchata (rice drink)","food","horchata drink","photo"],
["churros","churros","food","churros sugar","photo"],
["antojitos","Mexican street snacks","food","mexican street food","photo"],

# ─── BODY ───────────────────────────────────────────────────────────
["cabeza","head","body","human head profile","photo"],
["cara","face","body","face portrait","photo"],
["ojo","eye","body","eye close up","photo"],
["nariz","nose","body","nose face","photo"],
["boca","mouth","body","mouth lips smile","photo"],
["oreja","ear","body","ear close up","photo"],
["diente","tooth","body","white teeth smile","photo"],
["pelo","hair","body","hair flowing","photo"],
["cuello","neck","body","neck shoulder","photo"],
["hombro","shoulder","body","shoulder muscle","photo"],
["brazo","arm","body","arm muscle","photo"],
["mano","hand","body","open hand palm","photo"],
["dedo","finger","body","pointing finger","photo"],
["espalda","back","body","back person spine","photo"],
["estómago","stomach","body","stomach belly","photo"],
["pierna","leg","body","leg running","photo"],
["rodilla","knee","body","knee joint","photo"],
["pie","foot","body","bare foot","photo"],
["corazón","heart","body","heart anatomy","photo"],

# ─── HOME ───────────────────────────────────────────────────────────
["casa","house / home","home","house building exterior","photo"],
["cuarto","room","home","cozy room interior","photo"],
["cocina","kitchen","home","modern kitchen","photo"],
["baño","bathroom","home","bathroom clean","photo"],
["sala","living room","home","living room comfortable","photo"],
["cama","bed","home","made bed bedroom","photo"],
["mesa","table","home","wooden table","photo"],
["silla","chair","home","chair wooden","photo"],
["puerta","door","home","wooden door entrance","photo"],
["ventana","window","home","window light","photo"],
["llave","key","home","brass key","photo"],
["teléfono","telephone","home","phone call","photo"],
["computadora","computer","home","laptop computer desk","photo"],
["libro","book","home","open book reading","photo"],
["dinero","money","home","cash money bills","photo"],
["ropa","clothes / clothing","home","clothes wardrobe","photo"],
["camisa","shirt","home","button shirt","photo"],
["pantalones","pants / trousers","home","jeans pants","photo"],
["zapatos","shoes","home","pair of shoes","photo"],
["vestido","dress","home","dress fashion","photo"],
["sombrero","hat","home","sombrero hat","photo"],
["bolsa","bag / purse","home","handbag purse","photo"],

# ─── TIME ───────────────────────────────────────────────────────────
["tiempo","time / weather","time","clock time","photo"],
["hoy","today","time","","text"],
["ayer","yesterday","time","","text"],
["mañana","tomorrow / morning","time","sunrise morning","photo"],
["ahora","now","time","","text"],
["tarde","late / afternoon","time","afternoon sun","photo"],
["noche","night / evening","time","night moon city","photo"],
["semana","week","time","weekly calendar","photo"],
["mes","month","time","monthly calendar","photo"],
["año","year","time","year calendar","photo"],
["hora","hour","time","clock hour","photo"],
["minuto","minute","time","stopwatch minute","photo"],
["lunes","Monday","time","monday calendar","photo"],
["martes","Tuesday","time","tuesday calendar","photo"],
["miércoles","Wednesday","time","wednesday calendar","photo"],
["jueves","Thursday","time","thursday calendar","photo"],
["viernes","Friday","time","friday happy","photo"],
["sábado","Saturday","time","saturday weekend","photo"],
["domingo","Sunday","time","sunday rest","photo"],
["pronto","soon","time","","text"],
["después","after / later","time","","text"],
["antes","before","time","","text"],

# ─── PLACES ─────────────────────────────────────────────────────────
["ciudad","city","places","city skyline","photo"],
["pueblo","town / village","places","small mexican town","photo"],
["calle","street","places","street road city","photo"],
["tienda","store / shop","places","store shop","photo"],
["mercado","market","places","outdoor market colorful","photo"],
["supermercado","supermarket","places","supermarket aisle","photo"],
["restaurante","restaurant","places","restaurant dining","photo"],
["hospital","hospital","places","hospital building","photo"],
["escuela","school","places","school building children","photo"],
["iglesia","church","places","church building","photo"],
["parque","park","places","park green trees","photo"],
["aeropuerto","airport","places","airport terminal","photo"],
["hotel","hotel","places","hotel lobby","photo"],
["banco","bank","places","bank building","photo"],
["farmacia","pharmacy","places","pharmacy drugstore","photo"],
["playa","beach","places","beach ocean waves","photo"],
["montaña","mountain","places","mountain peak landscape","photo"],
["bosque","forest / woods","places","forest trees path","photo"],
["lago","lake","places","lake reflection","photo"],
["país","country","places","world map","photo"],
["México","Mexico","places","mexico flag culture","photo"],
["Estados Unidos","United States","places","united states flag","photo"],

# ─── TRANSPORTATION ────────────────────────────────────────────────
["carro","car","transport","car automobile","photo"],
["autobús","bus","transport","bus public transport","photo"],
["taxi","taxi","transport","yellow taxi cab","photo"],
["avión","airplane","transport","airplane flight","photo"],
["tren","train","transport","train railway","photo"],
["bicicleta","bicycle","transport","bicycle bike","photo"],
["metro","subway","transport","subway metro underground","photo"],
["barco","boat / ship","transport","sailboat water","photo"],
["camión","truck / bus (Mexico)","transport","cargo truck","photo"],

# ─── COMMON VERBS ──────────────────────────────────────────────────
["ser","to be (permanent)","verbs","","text"],
["estar","to be (temporary)","verbs","","text"],
["tener","to have","verbs","hands holding","photo"],
["hacer","to do / to make","verbs","craftsman making","photo"],
["ir","to go","verbs","person walking away","photo"],
["venir","to come","verbs","arriving running","photo"],
["querer","to want / to love","verbs","heart hands","photo"],
["poder","to be able to / can","verbs","strong arm muscle","photo"],
["saber","to know (a fact)","verbs","","text"],
["conocer","to know (person/place)","verbs","","text"],
["hablar","to speak / to talk","verbs","talking conversation","photo"],
["comer","to eat","verbs","eating food meal","photo"],
["beber","to drink","verbs","drinking water","photo"],
["dormir","to sleep","verbs","sleeping bed peaceful","photo"],
["trabajar","to work","verbs","office worker","photo"],
["vivir","to live","verbs","","text"],
["comprar","to buy","verbs","shopping bags","photo"],
["vender","to sell","verbs","selling market","photo"],
["leer","to read","verbs","reading book","photo"],
["escribir","to write","verbs","writing pen paper","photo"],
["escuchar","to listen","verbs","listening headphones","photo"],
["ver","to see / to watch","verbs","binoculars looking","photo"],
["pagar","to pay","verbs","paying cash register","photo"],
["buscar","to look for","verbs","searching magnifying glass","photo"],
["encontrar","to find","verbs","eureka discovery","photo"],
["llegar","to arrive","verbs","airport arrival","photo"],
["salir","to leave / to go out","verbs","exit door","photo"],
["entrar","to enter","verbs","entering doorway","photo"],
["abrir","to open","verbs","opening door","photo"],
["cerrar","to close","verbs","closing door","photo"],
["ayudar","to help","verbs","helping hand","photo"],
["necesitar","to need","verbs","","text"],
["gustar","to like / to please","verbs","thumbs up smile","photo"],
["llamar","to call","verbs","phone call","photo"],
["preguntar","to ask","verbs","question mark","photo"],
["contestar","to answer","verbs","","text"],
["pensar","to think","verbs","","text"],
["creer","to believe","verbs","","text"],
["esperar","to wait / to hope","verbs","waiting clock","photo"],
["dar","to give","verbs","giving gift hands","photo"],
["recibir","to receive","verbs","receiving package","photo"],
["tomar","to take / to drink","verbs","taking holding","photo"],
["usar","to use","verbs","using tool","photo"],
["correr","to run","verbs","running jogging","photo"],
["caminar","to walk","verbs","walking path","photo"],
["sentir","to feel","verbs","","text"],
["amar","to love","verbs","heart love","photo"],
["jugar","to play","verbs","playing game children","photo"],
["aprender","to learn","verbs","studying student","photo"],
["enseñar","to teach","verbs","teacher classroom","photo"],
["manejar","to drive","verbs","driving car steering","photo"],
["cocinar","to cook","verbs","cooking chef","photo"],
["limpiar","to clean","verbs","cleaning house","photo"],
["cambiar","to change","verbs","","text"],
["recordar","to remember","verbs","","text"],
["olvidar","to forget","verbs","","text"],
["entender","to understand","verbs","","text"],
["empezar","to begin / to start","verbs","starting line race","photo"],
["terminar","to finish / to end","verbs","finish line","photo"],

# ─── ADJECTIVES ────────────────────────────────────────────────────
["grande","big / large","adjectives","elephant size","photo"],
["pequeño","small / little","adjectives","tiny mouse","photo"],
["bueno","good","adjectives","thumbs up gold","photo"],
["malo","bad","adjectives","thumbs down","photo"],
["bonito","pretty / nice","adjectives","beautiful sunset","photo"],
["feo","ugly","adjectives","","text"],
["nuevo","new","adjectives","new product box","photo"],
["viejo","old","adjectives","old book antique","photo"],
["joven","young","adjectives","young person smiling","photo"],
["rápido","fast / quick","adjectives","fast race car","photo"],
["lento","slow","adjectives","turtle slow","photo"],
["fácil","easy","adjectives","","text"],
["difícil","difficult / hard","adjectives","","text"],
["rico","rich / delicious","adjectives","delicious gourmet","photo"],
["barato","cheap / inexpensive","adjectives","sale discount tag","photo"],
["caro","expensive","adjectives","luxury diamonds","photo"],
["limpio","clean","adjectives","spotless clean kitchen","photo"],
["sucio","dirty","adjectives","muddy dirty","photo"],
["caliente","hot / warm","adjectives","fire flame hot","photo"],
["frío","cold","adjectives","ice snow cold","photo"],
["cansado","tired","adjectives","tired sleepy yawn","photo"],
["contento","happy / content","adjectives","happy smiling","photo"],
["triste","sad","adjectives","sad crying","photo"],
["enojado","angry / mad","adjectives","angry frustrated","photo"],
["asustado","scared / afraid","adjectives","scared frightened","photo"],
["seguro","safe / sure","adjectives","safe vault secure","photo"],
["enfermo","sick / ill","adjectives","sick fever bed","photo"],
["sano","healthy","adjectives","healthy fit running","photo"],
["lleno","full","adjectives","full glass water","photo"],
["vacío","empty","adjectives","empty glass","photo"],
["abierto","open","adjectives","open sign shop","photo"],
["cerrado","closed","adjectives","closed sign","photo"],
["ocupado","busy / occupied","adjectives","busy office multitasking","photo"],
["libre","free / available","adjectives","","text"],
["listo","ready","adjectives","","text"],
["perdido","lost","adjectives","lost map confused","photo"],

# ─── CONNECTORS & FUNCTION WORDS ───────────────────────────────────
["y","and","connectors","","grammar","apples and oranges"],
["o","or","connectors","","grammar","tea or coffee"],
["pero","but","connectors","","grammar","small but powerful"],
["con","with","connectors","","grammar","rice with beans"],
["sin","without","connectors","","grammar","coffee without sugar"],
["para","for / in order to","connectors","","grammar","a gift for you"],
["por","by / for / through","connectors","","grammar","walk through the park"],
["en","in / at / on","connectors","","grammar","in the kitchen"],
["de","of / from","connectors","","grammar","made of wood"],
["a","to / at","connectors","","grammar","going to school"],
["que","that / which","connectors","","grammar","the book that I read"],
["muy","very","connectors","","text"],
["mucho","a lot / much","connectors","","text"],
["poco","a little / few","connectors","","text"],
["más","more","connectors","","text"],
["menos","less / fewer","connectors","","text"],
["todo","all / everything","connectors","","text"],
["nada","nothing","connectors","","text"],
["también","also / too","connectors","","text"],
["aquí","here","connectors","","text"],
["allí","there","connectors","","text"],
["solo","alone / only","connectors","","text"],
["siempre","always","connectors","","text"],
["nunca","never","connectors","","text"],
["a veces","sometimes","connectors","","text"],
["ya","already / now","connectors","","text"],
["aún","still / yet","connectors","","text"],

# ─── WEATHER ────────────────────────────────────────────────────────
["sol","sun","weather","bright sun sky","photo"],
["lluvia","rain","weather","rain falling","photo"],
["viento","wind","weather","wind blowing trees","photo"],
["nube","cloud","weather","fluffy cloud sky","photo"],
["nieve","snow","weather","snowfall winter","photo"],
["calor","heat","weather","hot desert sun","photo"],
["clima","climate / weather","weather","weather forecast","photo"],
["tormenta","storm","weather","lightning thunderstorm","photo"],
["niebla","fog","weather","foggy misty morning","photo"],

# ─── NATURE ─────────────────────────────────────────────────────────
["mar","sea / ocean","nature","ocean waves blue","photo"],
["río","river","nature","river flowing nature","photo"],
["árbol","tree","nature","tall tree green","photo"],
["flor","flower","nature","flower bloom colorful","photo"],
["hierba","grass","nature","green grass lawn","photo"],
["tierra","earth / soil / land","nature","soil dirt ground","photo"],
["cielo","sky","nature","blue sky clouds","photo"],
["luna","moon","nature","full moon night","photo"],
["estrella","star","nature","starry night sky","photo"],
["animal","animal","nature","wildlife animal","photo"],
["perro","dog","nature","golden retriever dog","photo"],
["gato","cat","nature","cute cat kitten","photo"],
["pájaro","bird","nature","colorful bird","photo"],
["pez","fish (live)","nature","tropical fish aquarium","photo"],

# ─── HEALTH ─────────────────────────────────────────────────────────
["médico","doctor","health","doctor stethoscope","photo"],
["enfermera","nurse","health","nurse smiling","photo"],
["medicina","medicine","health","medicine pills","photo"],
["dolor","pain / ache","health","headache pain","photo"],
["fiebre","fever","health","fever thermometer","photo"],
["gripe","flu / cold","health","sick tissue flu","photo"],
["alergia","allergy","health","allergic sneezing","photo"],
["embarazada","pregnant","health","pregnant woman belly","photo"],

# ─── WORK & SCHOOL ─────────────────────────────────────────────────
["trabajo","work / job","work","office desk work","photo"],
["jefe","boss / manager","work","boss manager suit","photo"],
["empleado","employee","work","employee worker","photo"],
["sueldo","salary","work","paycheck salary money","photo"],
["reunión","meeting","work","business meeting","photo"],
["estudiante","student","school","student studying","photo"],
["maestro","teacher (male)","school","teacher classroom male","photo"],
["maestra","teacher (female)","school","teacher classroom woman","photo"],
["clase","class / lesson","school","classroom lesson","photo"],
["tarea","homework","school","homework studying","photo"],
["examen","exam / test","school","exam test paper","photo"],

# ─── TECH ───────────────────────────────────────────────────────────
["internet","internet","tech","wifi network globe","photo"],
["celular","cell phone","tech","smartphone hand","photo"],
["aplicación","app","tech","smartphone apps icons","photo"],
["correo","email","tech","email envelope inbox","photo"],
["contraseña","password","tech","password lock security","photo"],
["red","network","tech","network nodes digital","photo"],

# ─── MEXICAN SLANG ─────────────────────────────────────────────────
["órale","okay / wow","mexican","","text"],
["ándale","come on / hurry","mexican","","text"],
["chido","cool / awesome","mexican","","text"],
["güey / wey","dude / guy","mexican","","text"],
["padre","cool (Mexican slang)","mexican","","text"],
["ahorita","right now / in a moment","mexican","","text"],
["mande","pardon? / yes?","mexican","","text"],
["cuate","buddy / pal","mexican","","text"],
["chela","beer (slang)","mexican","cold beer bottle","photo"],
["feria","change / coins (MX)","mexican","coins change pesos","photo"],
["neta","truth / for real","mexican","","text"],
["qué onda","what's up?","mexican","","text"],
["chamba","work / job (MX)","mexican","","text"],
["chido/a","cool person or thing","mexican","","text"],
["chavo","guy / young man","mexican","young man portrait","photo"],
["chava","girl / young woman","mexican","young woman portrait","photo"],
["no manches","no way!","mexican","","text"],
["híjole","wow / oh my!","mexican","","text"],
["pues","well... / so...","mexican","","text"],
["mero","right / exactly","mexican","","text"],

# ─── SHOPPING ──────────────────────────────────────────────────────
["precio","price","shopping","price tag","photo"],
["descuento","discount / sale","shopping","sale discount sign","photo"],
["recibo","receipt","shopping","cash register receipt","photo"],
["efectivo","cash","shopping","cash bills money","photo"],
["tarjeta","card (credit/debit)","shopping","credit card payment","photo"],
["tianguis","outdoor flea market","shopping","mexican market stalls","photo"],

# ─── DIRECTIONS ────────────────────────────────────────────────────
["derecha","right","directions","right arrow direction","photo"],
["izquierda","left","directions","left arrow direction","photo"],
["recto","straight ahead","directions","straight road","photo"],
["norte","north","directions","compass north","photo"],
["sur","south","directions","compass south","photo"],
["este","east","directions","compass east","photo"],
["oeste","west","directions","compass west","photo"],
["cerca","near / close","directions","","text"],
["lejos","far","directions","horizon distance road","photo"],
["esquina","corner","directions","street corner intersection","photo"],

# ─── EMERGENCY ─────────────────────────────────────────────────────
["ayuda","help!","emergency","help sign","photo"],
["auxilio","help! (urgent)","emergency","emergency alarm","photo"],
["fuego","fire","emergency","fire flames","photo"],
["policía","police","emergency","police officer","photo"],
["ambulancia","ambulance","emergency","ambulance emergency","photo"],
["peligro","danger","emergency","warning sign danger","photo"],
["emergencia","emergency","emergency","emergency siren","photo"],

# ═══════════════════════════════════════════════════════════════════
# WORDS 437+   NEW HIGH-FREQUENCY VOCABULARY
# ═══════════════════════════════════════════════════════════════════

# ─── MORE COMMON VERBS ─────────────────────────────────────────────
["aceptar","to accept","verbs","handshake agreement","photo"],
["acompañar","to accompany","verbs","friends walking together","photo"],
["aconsejar","to advise","verbs","mentor advice","photo"],
["acordar","to agree / remember","verbs","","text"],
["acostar","to put to bed","verbs","child bedtime","photo"],
["acostumbrar","to get used to","verbs","","text"],
["actuar","to act","verbs","actor stage","photo"],
["agradecer","to thank","verbs","grateful prayer hands","photo"],
["aguantar","to endure / put up with","verbs","","text"],
["alcanzar","to reach / achieve","verbs","reaching summit","photo"],
["alquilar","to rent","verbs","for rent sign","photo"],
["amenazar","to threaten","verbs","","text"],
["añadir","to add","verbs","plus sign math","photo"],
["andar","to walk / be","verbs","walking path forest","photo"],
["anunciar","to announce","verbs","megaphone announcement","photo"],
["apagar","to turn off","verbs","light switch off","photo"],
["aparecer","to appear","verbs","","text"],
["aplicar","to apply","verbs","application form","photo"],
["aportar","to contribute","verbs","","text"],
["aprovechar","to take advantage of","verbs","","text"],
["asegurar","to assure / insure","verbs","insurance contract","photo"],
["atacar","to attack","verbs","","text"],
["atender","to attend to / serve","verbs","customer service","photo"],
["aumentar","to increase","verbs","growth chart arrow up","photo"],
["averiguar","to find out","verbs","detective magnifying","photo"],
["bajar","to go down / lower","verbs","stairs going down","photo"],
["bañar","to bathe","verbs","bathtub bubbles","photo"],
["besar","to kiss","verbs","kiss couple","photo"],
["botar","to throw away","verbs","trash bin","photo"],
["brincar","to jump","verbs","jumping high","photo"],
["caer","to fall","verbs","falling leaf autumn","photo"],
["calentar","to heat / warm up","verbs","stove flame heat","photo"],
["callar","to be quiet / silence","verbs","finger lips silence","photo"],
["calmar","to calm","verbs","meditation calm","photo"],
["cargar","to carry / load","verbs","worker carrying box","photo"],
["casar","to marry","verbs","wedding rings","photo"],
["causar","to cause","verbs","","text"],
["cenar","to have dinner","verbs","dinner table family","photo"],
["chocar","to crash / collide","verbs","car crash collision","photo"],
["cobrar","to charge / collect (payment)","verbs","cashier money","photo"],
["coger","to grab / catch","verbs","catching ball hands","photo"],
["colgar","to hang","verbs","hanging clothes line","photo"],
["colocar","to place / put","verbs","placing object shelf","photo"],
["comenzar","to begin","verbs","starting line race","photo"],
["componer","to compose","verbs","composer music notes","photo"],
["comportar","to behave","verbs","","text"],
["comunicar","to communicate","verbs","communication speech","photo"],
["concentrar","to concentrate","verbs","focus concentration","photo"],
["confiar","to trust","verbs","trust handshake","photo"],
["congelar","to freeze","verbs","ice frozen","photo"],
["conocer","to know / meet","verbs","","text"],
["conseguir","to obtain / achieve","verbs","trophy success","photo"],
["considerar","to consider","verbs","","text"],
["construir","to build / construct","verbs","construction site","photo"],
["contar","to count / tell","verbs","counting fingers","photo"],
["controlar","to control","verbs","control panel buttons","photo"],
["convertir","to convert","verbs","","text"],
["corregir","to correct","verbs","red pen correcting","photo"],
["cortar","to cut","verbs","scissors cutting paper","photo"],
["crear","to create","verbs","artist creating","photo"],
["crecer","to grow","verbs","plant seedling growing","photo"],
["criar","to raise (a child)","verbs","parent child raising","photo"],
["cuidar","to take care of","verbs","caring mother child","photo"],
["cumplir","to fulfill","verbs","checklist done","photo"],
["deber","to owe / must","verbs","","text"],
["decidir","to decide","verbs","crossroads decision","photo"],
["decir","to say / tell","verbs","talking conversation","photo"],
["defender","to defend","verbs","shield protection","photo"],
["dejar","to leave / let","verbs","","text"],
["demostrar","to demonstrate / prove","verbs","","text"],
["depender","to depend","verbs","","text"],
["describir","to describe","verbs","","text"],
["descansar","to rest","verbs","resting hammock","photo"],
["descubrir","to discover","verbs","explorer discovery","photo"],
["desear","to wish / desire","verbs","wishing star","photo"],
["desarrollar","to develop","verbs","","text"],
["deshacer","to undo","verbs","","text"],
["despedir","to fire / say goodbye","verbs","goodbye waving","photo"],
["despertar","to wake up","verbs","alarm clock morning","photo"],
["destruir","to destroy","verbs","demolition crumbling","photo"],
["detener","to stop","verbs","stop sign","photo"],
["devolver","to return (something)","verbs","return package","photo"],
["dibujar","to draw","verbs","drawing pencil sketch","photo"],
["dirigir","to direct / lead","verbs","conductor orchestra","photo"],
["discutir","to discuss / argue","verbs","arguing debate","photo"],
["disfrutar","to enjoy","verbs","enjoying beach vacation","photo"],
["disculpar","to forgive / excuse","verbs","","text"],
["dividir","to divide","verbs","division split","photo"],
["doler","to hurt","verbs","headache pain","photo"],
["doblar","to fold / bend","verbs","folded paper origami","photo"],
["dudar","to doubt","verbs","","text"],
["echar","to throw","verbs","throwing ball","photo"],
["elegir","to choose","verbs","choice options","photo"],
["enamorar","to fall in love","verbs","couple in love","photo"],
["encantar","to delight / love","verbs","","text"],
["encender","to turn on","verbs","light switch on","photo"],
["enojar","to anger","verbs","angry face","photo"],
["ensayar","to rehearse","verbs","band rehearsal","photo"],
["enterar","to inform / find out","verbs","","text"],
["enviar","to send","verbs","envelope mail send","photo"],
["envolver","to wrap","verbs","wrapping gift","photo"],
["equivocar","to be wrong / mistake","verbs","","text"],
["escapar","to escape","verbs","running escape","photo"],
["esconder","to hide","verbs","hide and seek child","photo"],
["estudiar","to study","verbs","student studying books","photo"],
["evitar","to avoid","verbs","","text"],
["existir","to exist","verbs","","text"],
["explicar","to explain","verbs","teacher explaining","photo"],
["expresar","to express","verbs","","text"],
["fabricar","to manufacture","verbs","factory production","photo"],
["faltar","to be missing / lacking","verbs","","text"],
["fijar","to fix / set","verbs","","text"],
["firmar","to sign","verbs","signing contract pen","photo"],
["fumar","to smoke","verbs","cigarette smoke","photo"],
["funcionar","to function / work","verbs","gears mechanism","photo"],
["ganar","to win / earn","verbs","trophy winner","photo"],
["gastar","to spend (money)","verbs","spending shopping","photo"],
["girar","to turn / spin","verbs","steering wheel turn","photo"],
["gritar","to shout / scream","verbs","shouting megaphone","photo"],
["guardar","to keep / save","verbs","safe vault store","photo"],
["guiar","to guide","verbs","guide pointing path","photo"],
["habitar","to inhabit","verbs","","text"],
["heredar","to inherit","verbs","family heirloom","photo"],
["herir","to wound / hurt","verbs","bandage injury","photo"],
["huir","to flee","verbs","escape running","photo"],
["imaginar","to imagine","verbs","","text"],
["importar","to matter / import","verbs","","text"],
["impresionar","to impress","verbs","","text"],
["incluir","to include","verbs","","text"],
["informar","to inform","verbs","news bulletin","photo"],
["insistir","to insist","verbs","","text"],
["intentar","to try","verbs","","text"],
["interesar","to interest","verbs","","text"],
["invitar","to invite","verbs","invitation envelope","photo"],
["lavar","to wash","verbs","washing hands soap","photo"],
["levantar","to lift / raise","verbs","lifting weights","photo"],
["llenar","to fill","verbs","filling glass water","photo"],
["llevar","to carry / wear","verbs","carrying bags","photo"],
["llorar","to cry","verbs","tears crying","photo"],
["lograr","to achieve","verbs","summit success","photo"],
["luchar","to fight / struggle","verbs","boxers fighting","photo"],
["mandar","to send / command","verbs","","text"],
["matar","to kill","verbs","","text"],
["medir","to measure","verbs","tape measure ruler","photo"],
["mentir","to lie","verbs","crossed fingers behind","photo"],
["meter","to put in","verbs","","text"],
["mirar","to look at / watch","verbs","looking watching","photo"],
["morir","to die","verbs","","text"],
["mostrar","to show","verbs","presentation showing","photo"],
["mover","to move","verbs","moving boxes","photo"],
["nacer","to be born","verbs","newborn baby","photo"],
["nadar","to swim","verbs","swimming pool","photo"],
["negar","to deny","verbs","","text"],
["notar","to notice","verbs","","text"],
["obtener","to obtain","verbs","","text"],
["ocurrir","to occur / happen","verbs","","text"],
["ofrecer","to offer","verbs","offering hand gift","photo"],
["oír","to hear","verbs","ear listening","photo"],
["oler","to smell","verbs","smelling flower nose","photo"],
["olvidar","to forget","verbs","","text"],
["organizar","to organize","verbs","organized desk neat","photo"],
["pagar","to pay","verbs","paying card terminal","photo"],
["parar","to stop","verbs","stop sign red","photo"],
["parecer","to seem / look like","verbs","","text"],
["partir","to leave / split","verbs","","text"],
["pasar","to pass / happen","verbs","","text"],
["pedir","to ask for / request","verbs","","text"],
["pegar","to hit / stick","verbs","glue stick","photo"],
["perder","to lose","verbs","lost direction confusion","photo"],
["permitir","to permit / allow","verbs","permission allowed sign","photo"],
["pesar","to weigh","verbs","scale weighing","photo"],
["pintar","to paint","verbs","artist painting","photo"],
["planchar","to iron","verbs","ironing clothes","photo"],
["planear","to plan","verbs","planning calendar notes","photo"],
["practicar","to practice","verbs","practice music piano","photo"],
["preferir","to prefer","verbs","","text"],
["preocupar","to worry","verbs","worried thinking","photo"],
["preparar","to prepare","verbs","cooking prep ingredients","photo"],
["presentar","to present / introduce","verbs","presentation speaker","photo"],
["prestar","to lend","verbs","","text"],
["probar","to try / taste","verbs","tasting food chef","photo"],
["producir","to produce","verbs","factory production","photo"],
["prohibir","to prohibit","verbs","forbidden sign","photo"],
["prometer","to promise","verbs","pinky promise","photo"],
["proteger","to protect","verbs","shield protection guard","photo"],
["quedar","to remain / stay","verbs","","text"],
["quitar","to take away / remove","verbs","","text"],
["realizar","to carry out / realize","verbs","","text"],
["recoger","to pick up / collect","verbs","picking up trash","photo"],
["reconocer","to recognize","verbs","","text"],
["recorrer","to travel / go through","verbs","road trip travel","photo"],
["regalar","to give as a gift","verbs","wrapped gift bow","photo"],
["regresar","to return / come back","verbs","return arrow","photo"],
["reír","to laugh","verbs","laughing joy","photo"],
["repetir","to repeat","verbs","","text"],
["resolver","to resolve / solve","verbs","puzzle solving","photo"],
["respirar","to breathe","verbs","breathing meditation","photo"],
["responder","to respond","verbs","","text"],
["resultar","to result / turn out","verbs","","text"],
["robar","to steal","verbs","thief mask","photo"],
["romper","to break","verbs","broken glass","photo"],
["saltar","to jump","verbs","jumping leap","photo"],
["secar","to dry","verbs","towel drying","photo"],
["seguir","to follow / continue","verbs","follow footsteps","photo"],
["sentar","to sit","verbs","sitting chair person","photo"],
["servir","to serve","verbs","serving food waiter","photo"],
["soñar","to dream","verbs","dreaming sleep clouds","photo"],
["sonreír","to smile","verbs","smiling face happy","photo"],
["subir","to go up / rise","verbs","stairs climbing up","photo"],
["sufrir","to suffer","verbs","","text"],
["suponer","to suppose","verbs","","text"],
["tardar","to take time / be late","verbs","clock late hurry","photo"],
["tirar","to throw / pull","verbs","throwing ball baseball","photo"],
["tocar","to touch / play","verbs","touching texture","photo"],
["tratar","to try / treat","verbs","","text"],
["unir","to unite / join","verbs","puzzle pieces fitting","photo"],
["valer","to be worth","verbs","","text"],
["viajar","to travel","verbs","suitcase airport travel","photo"],
["visitar","to visit","verbs","visiting friend doorbell","photo"],
["volar","to fly","verbs","bird flying sky","photo"],
["volver","to return","verbs","","text"],
["votar","to vote","verbs","ballot box voting","photo"],

# ─── MORE ADJECTIVES ───────────────────────────────────────────────
["alto","tall / high","adjectives","tall building skyscraper","photo"],
["bajo","short / low","adjectives","","text"],
["ancho","wide","adjectives","wide road highway","photo"],
["estrecho","narrow","adjectives","narrow alley","photo"],
["delgado","thin","adjectives","thin person slim","photo"],
["gordo","fat","adjectives","","text"],
["fuerte","strong","adjectives","strong muscle arm","photo"],
["débil","weak","adjectives","","text"],
["duro","hard / tough","adjectives","hard stone rock","photo"],
["suave","soft / smooth","adjectives","soft pillow plush","photo"],
["pesado","heavy","adjectives","heavy weight barbell","photo"],
["ligero","light (weight)","adjectives","feather light","photo"],
["oscuro","dark","adjectives","dark night cave","photo"],
["claro","clear / light","adjectives","clear water glass","photo"],
["brillante","bright / brilliant","adjectives","bright sun shining","photo"],
["importante","important","adjectives","","text"],
["necesario","necessary","adjectives","","text"],
["posible","possible","adjectives","","text"],
["imposible","impossible","adjectives","","text"],
["común","common","adjectives","","text"],
["raro","rare / strange","adjectives","","text"],
["popular","popular","adjectives","crowded popular event","photo"],
["famoso","famous","adjectives","celebrity red carpet","photo"],
["mejor","better / best","adjectives","first place podium","photo"],
["peor","worse / worst","adjectives","","text"],
["mismo","same","adjectives","","text"],
["diferente","different","adjectives","","text"],
["igual","equal / same","adjectives","equal sign math","photo"],
["natural","natural","adjectives","nature forest leaves","photo"],
["artificial","artificial","adjectives","plastic flowers fake","photo"],
["real","real","adjectives","","text"],
["falso","false / fake","adjectives","","text"],
["verdadero","true","adjectives","","text"],
["correcto","correct","adjectives","checkmark green correct","photo"],
["incorrecto","incorrect","adjectives","red x wrong mark","photo"],
["completo","complete","adjectives","","text"],
["incompleto","incomplete","adjectives","","text"],
["claro","clear","adjectives","clear sky transparent","photo"],
["público","public","adjectives","public square crowd","photo"],
["privado","private","adjectives","private sign no entry","photo"],
["profesional","professional","adjectives","professional suit office","photo"],
["amable","kind / friendly","adjectives","kind smile gesture","photo"],
["simpático","nice / pleasant","adjectives","friendly smile warm","photo"],
["inteligente","intelligent","adjectives","","text"],
["tonto","silly / dumb","adjectives","","text"],
["loco","crazy","adjectives","","text"],
["normal","normal","adjectives","","text"],
["especial","special","adjectives","gold star special","photo"],
["principal","main / principal","adjectives","","text"],
["último","last","adjectives","","text"],
["primero","first","adjectives","first place gold","photo"],
["segundo","second","adjectives","silver medal second","photo"],
["tercero","third","adjectives","bronze medal third","photo"],
["próximo","next","adjectives","","text"],

# ─── ABSTRACT NOUNS ────────────────────────────────────────────────
["idea","idea","abstract","","text"],
["manera","way / manner","abstract","","text"],
["forma","form / shape","abstract","","text"],
["modo","manner / way","abstract","","text"],
["momento","moment","abstract","","text"],
["razón","reason","abstract","","text"],
["causa","cause","abstract","","text"],
["resultado","result","abstract","","text"],
["situación","situation","abstract","","text"],
["caso","case","abstract","","text"],
["punto","point","abstract","","text"],
["parte","part","abstract","","text"],
["mitad","half","abstract","half pie chart","photo"],
["total","total","abstract","","text"],
["número","number","abstract","","text"],
["color","color","abstract","","text"],
["nombre","name","abstract","","text"],
["palabra","word","abstract","","text"],
["historia","story / history","abstract","old history book","photo"],
["cuenta","account / story","abstract","","text"],
["pregunta","question","abstract","question mark","photo"],
["respuesta","answer","abstract","","text"],
["problema","problem","abstract","","text"],
["solución","solution","abstract","","text"],
["verdad","truth","abstract","","text"],
["mentira","lie","abstract","","text"],
["paz","peace","abstract","dove peace symbol","photo"],
["guerra","war","abstract","","text"],
["amor","love","abstract","red heart","photo"],
["odio","hate","abstract","","text"],
["alegría","joy / happiness","abstract","joyful celebration","photo"],
["esperanza","hope","abstract","","text"],
["miedo","fear","abstract","","text"],
["esfuerzo","effort","abstract","","text"],
["fuerza","strength / force","abstract","strong arm muscle","photo"],
["poder","power","abstract","","text"],
["energía","energy","abstract","lightning bolt energy","photo"],
["calidad","quality","abstract","","text"],
["cantidad","quantity","abstract","","text"],
["nivel","level","abstract","level bar progress","photo"],
["plan","plan","abstract","planning chart","photo"],
["proyecto","project","abstract","","text"],
["sistema","system","abstract","","text"],
["regla","rule","abstract","ruler measure","photo"],
["ley","law","abstract","gavel court justice","photo"],
["orden","order","abstract","","text"],
["paz","peace","abstract","dove peace","photo"],

# ─── EMOTIONS ──────────────────────────────────────────────────────
["sentimiento","feeling","emotion","","text"],
["emoción","emotion","emotion","","text"],
["alegre","cheerful","emotion","cheerful smile happy","photo"],
["feliz","happy","emotion","happy smiling face","photo"],
["nervioso","nervous","emotion","nervous biting nails","photo"],
["calmado","calm","emotion","calm meditation peace","photo"],
["preocupado","worried","emotion","worried thoughtful","photo"],
["aburrido","bored","emotion","bored yawning","photo"],
["divertido","fun / amusing","emotion","amusement park fun","photo"],
["sorprendido","surprised","emotion","surprised shocked face","photo"],
["confundido","confused","emotion","confused thinking","photo"],
["orgulloso","proud","emotion","proud champion","photo"],
["avergonzado","embarrassed","emotion","","text"],
["celoso","jealous","emotion","","text"],

# ─── ANIMALS ───────────────────────────────────────────────────────
["caballo","horse","animals","running horse field","photo"],
["vaca","cow","animals","cow grazing pasture","photo"],
["toro","bull","animals","bull strong horns","photo"],
["cerdo","pig","animals","pig farm","photo"],
["oveja","sheep","animals","sheep wool grass","photo"],
["cabra","goat","animals","goat field","photo"],
["pollo","chicken (animal)","animals","chicken hen farm","photo"],
["pato","duck","animals","duck pond","photo"],
["conejo","rabbit","animals","fluffy rabbit","photo"],
["ratón","mouse","animals","cute mouse","photo"],
["león","lion","animals","lion mane savanna","photo"],
["tigre","tiger","animals","tiger stripes","photo"],
["oso","bear","animals","brown bear forest","photo"],
["lobo","wolf","animals","gray wolf","photo"],
["zorro","fox","animals","red fox","photo"],
["mono","monkey","animals","monkey tree","photo"],
["elefante","elephant","animals","elephant savanna","photo"],
["serpiente","snake","animals","snake coiled","photo"],
["abeja","bee","animals","honeybee flower","photo"],
["mariposa","butterfly","animals","colorful butterfly","photo"],
["araña","spider","animals","spider web","photo"],
["hormiga","ant","animals","ants column","photo"],
["mosca","fly","animals","housefly closeup","photo"],

# ─── AGRICULTURE & FARMING ─────────────────────────────────────────
["agricultura","agriculture","agriculture","farmland aerial fields","photo"],
["granja","farm","agriculture","farm red barn","photo"],
["granjero","farmer","agriculture","farmer with crops","photo"],
["campo","field / countryside","agriculture","wheat field golden","photo"],
["tierra","soil / earth","agriculture","fertile soil hands","photo"],
["cultivo","crop / cultivation","agriculture","crop rows growing","photo"],
["cosecha","harvest","agriculture","harvest wheat sickle","photo"],
["sembrar","to sow / plant","agriculture","sowing seeds hand","photo"],
["semilla","seed","agriculture","seeds packet","photo"],
["plantar","to plant","agriculture","planting sapling","photo"],
["regar","to water (plants)","agriculture","watering plants can","photo"],
["riego","irrigation","agriculture","irrigation sprinklers field","photo"],
["abono","fertilizer","agriculture","fertilizer compost","photo"],
["abonar","to fertilize","agriculture","spreading fertilizer","photo"],
["arado","plow","agriculture","plow tractor field","photo"],
["arar","to plow","agriculture","plowing tractor","photo"],
["tractor","tractor","agriculture","red tractor field","photo"],
["pala","shovel","agriculture","shovel garden tool","photo"],
["rastrillo","rake","agriculture","garden rake leaves","photo"],
["azadón","hoe","agriculture","garden hoe","photo"],
["cosechar","to harvest","agriculture","farmers harvesting","photo"],
["grano","grain","agriculture","wheat grain pile","photo"],
["trigo","wheat","agriculture","wheat stalks golden","photo"],
["maíz","corn / maize","agriculture","corn stalks field","photo"],
["cebada","barley","agriculture","barley field","photo"],
["avena","oats","agriculture","oat bowl","photo"],
["heno","hay","agriculture","hay bales field","photo"],
["pasto","grass / pasture","agriculture","green pasture cattle","photo"],
["ganado","cattle / livestock","agriculture","cattle herd","photo"],
["establo","stable / barn","agriculture","horse stable barn","photo"],
["pesticida","pesticide","agriculture","","text"],
["plaga","pest / plague","agriculture","crop pests insects","photo"],
["huerto","orchard / vegetable garden","agriculture","vegetable garden rows","photo"],
["jardín","garden","agriculture","flower garden beautiful","photo"],
["invernadero","greenhouse","agriculture","greenhouse plants","photo"],
["fruta","fruit","agriculture","mixed fresh fruits","photo"],
["verdura","vegetable","agriculture","fresh vegetables basket","photo"],
["raíz","root","agriculture","tree roots earth","photo"],
["hoja","leaf","agriculture","green leaf detail","photo"],
["rama","branch","agriculture","tree branches","photo"],
["tronco","trunk","agriculture","tree trunk bark","photo"],
["agricultor","farmer (formal)","agriculture","farmer field","photo"],
["temporada","season","agriculture","four seasons collage","photo"],
["seca","dry / drought","agriculture","dry cracked earth","photo"],
["lluvia","rainfall (farming)","agriculture","rain falling crops","photo"],

# ─── WINE & WINEMAKING ────────────────────────────────────────────
["viña","vineyard","wine","vineyard rows hills","photo"],
["viñedo","vineyard","wine","vineyard sunset rows","photo"],
["vid","grapevine","wine","grapevine leaves","photo"],
["uva","grape","wine","grape cluster purple","photo"],
["racimo","cluster (of grapes)","wine","grape cluster vine","photo"],
["vendimia","grape harvest","wine","grape harvest workers","photo"],
["vendimiar","to harvest grapes","wine","harvesting grapes basket","photo"],
["bodega","winery / cellar","wine","wine cellar barrels","photo"],
["barril","barrel","wine","oak wine barrel","photo"],
["barrica","wine barrel (small)","wine","wine barrels aging","photo"],
["roble","oak","wine","oak tree","photo"],
["fermentación","fermentation","wine","fermentation tanks winery","photo"],
["fermentar","to ferment","wine","fermenting wine bubbles","photo"],
["levadura","yeast","wine","yeast bubbles","photo"],
["mosto","grape must","wine","grape must pressing","photo"],
["prensar","to press","wine","grape press machine","photo"],
["prensa","press (winery)","wine","wine press wooden","photo"],
["añejar","to age (wine)","wine","aged wine bottle dusty","photo"],
["añejo","aged","wine","aged wine bottles cellar","photo"],
["crianza","aging period","wine","wine cellar aging","photo"],
["reserva","reserve (wine)","wine","reserve wine bottle label","photo"],
["tinto","red (wine)","wine","red wine glass dark","photo"],
["blanco (vino)","white (wine)","wine","white wine glass","photo"],
["rosado","rosé (wine)","wine","rosé wine pink","photo"],
["espumoso","sparkling","wine","sparkling wine bubbles","photo"],
["seco","dry (wine)","wine","","text"],
["dulce (vino)","sweet (wine)","wine","dessert wine","photo"],
["taninos","tannins","wine","red wine swirl","photo"],
["cuerpo","body (of wine)","wine","","text"],
["aroma","aroma","wine","wine smell tasting","photo"],
["sabor","flavor / taste","wine","wine tasting glass","photo"],
["catador","wine taster","wine","wine sommelier tasting","photo"],
["catar","to taste (wine)","wine","wine tasting glass swirl","photo"],
["cata","wine tasting","wine","wine tasting flight","photo"],
["botella","bottle","wine","wine bottle","photo"],
["corcho","cork","wine","wine cork closeup","photo"],
["sacacorchos","corkscrew","wine","corkscrew opening bottle","photo"],
["copa","wine glass","wine","red wine glass stem","photo"],
["decantar","to decant","wine","decanter wine pouring","photo"],
["decantador","decanter","wine","crystal wine decanter","photo"],
["etiqueta","label","wine","wine bottle label","photo"],
["cosecha (vino)","vintage / harvest year","wine","wine vintage year label","photo"],
["añada","vintage","wine","wine vintage cellar","photo"],
["clima (vid)","wine climate","wine","vineyard climate hills","photo"],
["terruño","terroir","wine","vineyard soil terroir","photo"],
["pendiente","slope (vineyard)","wine","vineyard hillside slope","photo"],
["sommelier","sommelier","wine","sommelier wine pouring","photo"],
["maridaje","food pairing","wine","wine cheese pairing","photo"],
["sulfitos","sulfites","wine","","text"],

]

